// usecases/react/src/App.js
import './App.css';
import { BrowserRouter, Route, Routes } from "react-router-dom";
import Airports from "./components/airports";
import { AirportsWrapper } from "./components/airportsWrapper";
import { DozerProvider } from "@dozerjs/dozer-react";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src="https://getdozer.io/img/logo.svg" className="App-logo" alt="logo" />
        <DozerProvider value={{
          serverAddress: 'http://localhost:62998',
        }}>
          <BrowserRouter>
            <Routes>
              <Route index element={<Airports />} />
              <Route element={<AirportsWrapper />} path={"/airports"} />
            </Routes>
          </BrowserRouter>
        </DozerProvider>
      </header>
    </div>
  );
}

export default App;

// usecases/vue/src/App.vue
<script setup lang="ts">
import { DozerProvider } from '@dozerjs/dozer-vue';
import { RouterView } from 'vue-router';
</script>

<template>
  <header class="app-header">
    <img src="https://getdozer.io/img/logo.svg" className="App-logo" alt="logo" />
  </header>
  <main class="app-content">
    <DozerProvider :value="{
      serverAddress: 'http://localhost:62998',
    }">
      <RouterView />
    </DozerProvider>
  </main>
</template>

<style scoped>
.app-logo {
  height: 10vmin;
  pointer-events: none;
  padding: 10px;
}

.app-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
  text-align: center;
  margin-bottom: 16px;
}

.app-content {
  flex: 1;
}
</style>
