// usecases/snowflake-react/src/components/departuresCount.js
import { Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from "@mui/material";
import { useEffect, useState } from "react";
import { useDozerEvent, useDozerQuery } from "@dozerjs/dozer-react";
import { Order } from "@dozerjs/dozer/lib/esm/query_helper";
import { OperationType, Type } from "@dozerjs/dozer/lib/esm/generated/protos/types";

function DeparturesCount() {
  let query = { orderBy: { start: Order.ASC } };
  const { records, fields, connect } = useDozerQuery('departures_count', query);
  const { stream } = useDozerEvent([{ endpoint: 'departures_count' }]);
  connect(stream)


  if (fields.length === 0) {
    return null;
  }

  return <div>
    <TableContainer component={Paper}>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            {fields.map(f => <TableCell>{f.getName()}</TableCell>)}
          </TableRow>
        </TableHead>
        <TableBody>
          {records.map(r => (
            <TableRow
              key={r.__dozer_record_id}
              sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
            >
              {fields.map(f => <>
                {f.getName() === 'start' ? <TableCell>{r[f.getName()]}:00 to {r[f.getName()] + 4}:00 </TableCell> :
                  <>
                    {(f.getTyp() === Type.Point) && <TableCell key={f.getName()}>{r[f.getName()].getX()}, {r[f.getName()].getY()}</TableCell>}
                    {(f.getTyp() !== Type.Point) && <TableCell key={f.getName()}>{r[f.getName()]}</TableCell>}
                  </>
                }

              </>)}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  </div>;
}

export default DeparturesCount;

// usecases/vue/src/components/DeparturesCount.vue
<script setup lang="ts">
import { Order } from "@dozerjs/dozer";
import { useDozerEvent, useDozerQuery } from "@dozerjs/dozer-vue";
import { Type } from "@dozerjs/dozer/lib/esm/generated/protos/types_pb";
import EmptyCard from "./EmptyCard.vue";

const { records, fields, connect } = useDozerQuery<Record<string, any>>('departures_count', { orderBy: { start: Order.ASC } });
const { stream } = useDozerEvent([{ endpoint: 'departures_count' }]);
connect(stream.value);

</script> 

<template>
  <v-table v-if="fields">
    <thead>
      <tr>
        <th v-for="f in fields" :key="f.getName()">
          {{ f.getName() }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="r in records" :key="r.__dozer_record_id">
        <td v-for="f in fields" :key="f.getName()">
          {{
            f.getTyp() === Type.POINT
            ? `${r[f.getName()].getX()}, ${r[f.getName()].getY()}`
            : (
              f.getName() === 'start'
                ? `${r[f.getName()]}:00 to ${r[f.getName()] + 4}:00 `
                : r[f.getName()]
            )
          }}
        </td>
      </tr>
    </tbody>
  </v-table>
  <EmptyCard v-if="fields === undefined" />
</template>
