// usecases/react/src/components/departuresCount.js
import { Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from "@mui/material";
import { useEffect, useState } from "react";
import { useOnEvent, useQueryCommon } from "@dozerjs/dozer-react";
import { Order } from "@dozerjs/dozer/lib/esm/query_helper";
import { OperationType, Type } from "@dozerjs/dozer/lib/esm/generated/protos/types";

function DeparturesCount() {
  const [counts, setCounts] = useState([]);
  let query = {orderBy: {start: Order.ASC}};
  const {records, fields} = useQueryCommon('departures_count', query);

  useOnEvent('departures_count', (data, fields, primaryIndexKeys, mapper) => {
    if (fields.length) {
      setCounts(records => {
        if (data.getTyp() === OperationType.UPDATE) {
          let oldValue = mapper.mapRecord(data.getOld().getValuesList());
          let existingIndex = records.findIndex(v => v[primaryIndexKeys[0]] === oldValue[primaryIndexKeys[0]])

          if (records.length > 0) {
            if (existingIndex > -1) {
              records[existingIndex] = mapper.mapRecord(data.getNew().getValuesList());
              return [...records];
            } else {
              return [...records, mapper.mapRecord(data.getNew().getValuesList())];
            }
          }
        } else if (data.getTyp() === OperationType.INSERT) {
          return [...records, mapper.mapRecord(data.getNew().getValuesList())];
        }

        return records;
      });
    }
  });


  useEffect(() => {
    setCounts(records);
  }, [records])

  if (fields.length === 0) {
    return null;
  }

  return <div>
    <TableContainer component={Paper}>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            { fields.map(f => <TableCell>{f.getName()}</TableCell>) }
          </TableRow>
        </TableHead>
        <TableBody>
          { counts.map(r => (
            <TableRow
              key={ r[fields[0].getName()] }
              sx={ { '&:last-child td, &:last-child th': { border: 0 } } }
            >
              { fields.map(f => <>
                {f.getName() === 'start' ? <TableCell>{r[f.getName()]}:00 to {r[f.getName()] + 4}:00 </TableCell>:
                  <>
                    {(f.getTyp() === Type.Point) && <TableCell>{r[f.getName()].getX()}, {r[f.getName()].getY()}</TableCell>}
                {(f.getTyp() !== Type.Point) && <TableCell>{r[f.getName()]}</TableCell>}
                  </>
                }

              </>)}
            </TableRow>
          )) }
        </TableBody>
      </Table>
    </TableContainer>
  </div>;
}

export default DeparturesCount;

// usecases/vue/src/components/DeparturesCount.vue
<script setup lang="ts">
import { Order } from "@dozerjs/dozer";
import { useDozerEndpoint } from "@dozerjs/dozer-vue";
import { EventType, Type } from "@dozerjs/dozer/lib/esm/generated/protos/types_pb";
import EmptyCard from "./EmptyCard.vue";

const { records, fields } = useDozerEndpoint('departures_count', {
  query: { orderBy: { start: Order.ASC } },
  watch: EventType.ALL,
});

</script> 

<template>
  <v-table v-if="fields">
    <thead>
      <tr>
        <th v-for="f in fields" :key="f.getName()">
          {{ f.getName() }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="r in records" :key="(r as Record<string, any>)[fields[0].getName()]">
        <td v-for="f in fields" :key="f.getName()">
          {{ 
            f.getTyp() === Type.POINT 
              ? `${(r as Record<string, any>)[f.getName()].getX()}, ${(r as Record<string, any>)[f.getName()].getY()}` 
              : (
                f.getName() === 'start'
                  ? `${(r as Record<string, any>)[f.getName()]}:00 to ${(r as Record<string, any>)[f.getName()] + 4}:00 `
                  : (r as Record<string, any>)[f.getName()] 
              )
          }}
        </td>
      </tr>
    </tbody>
  </v-table>
  <EmptyCard v-if="fields === undefined"/>
</template>
